[package]
name = "pretty-log"
version = "0.1.0"
authors = ["Fredrik Østrem <fredrik.ostrem@cognite.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde = { version = "1.0.91", features = [ "derive" ] }
serde_json = "1.0.39"
chrono = { version = "0.4.6", features = [ "serde" ] }
