[package]
name = "git-corun"
version = "0.1.0"
authors = ["Fredrik Østrem <fredrik.ostrem@cognite.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/frxstrem/tools"

[dependencies]
clap = "2.33.0"
tempdir = "0.3.7"
