[package]
name = "luxa"
version = "0.2.0"
authors = ["Fredrik Østrem <fredrik.ostrem@cognite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.103", features = [ "derive" ] }
tokio = { version = "0.2.13", features = [ "macros" ] }
clap = "2.33.0"
hidapi = "1.0.1"
