[package]
name = "luxa"
version = "0.2.0"
authors = ["Fredrik Østrem <fredrik.ostrem@cognite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luxa-core = { path = "../../lib/luxa-core", features = [ "hid" ] }
clap = "2.33.0"
tokio = { version = "0.2.4", features = [ "macros" ] }
