[package]
name = "pretty-log"
version = "0.2.0"
authors = ["Fredrik Østrem <fredrik.ostrem@cognite.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/frxstrem/tools"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.9"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
chrono = { version = "0.4.10", features = ["serde"] }
libc = "0.2.67"
crossbeam = "0.7.3"
