[package]
name = "pretty-log"
version = "0.1.0"
authors = ["Fredrik Østrem <fredrik.ostrem@cognite.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/frxstrem/tools"

[dependencies]
clap = "2.33.0"
serde = { version = "1.0.91", features = [ "derive" ] }
serde_json = "1.0.39"
chrono = { version = "0.4.6", features = [ "serde" ] }
libc = "0.2.55"
regex = "1.3.4"
crossbeam = "0.7.1"
lazy_static = "1.4.0"
